/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-03 at 18:32:33 UTC 
 * Modify at your own risk.
 */

package com.appspot.qr_search_api.item;

/**
 * Service definition for Item (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ItemRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Item extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the item library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://qr-search-api.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "item/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Item(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Item(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the ItemService collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Item item = new Item(...);}
   *   {@code Item.ItemService.List request = item.itemService().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public ItemService itemService() {
    return new ItemService();
  }

  /**
   * The "itemService" collection of methods.
   */
  public class ItemService {

    /**
     * Create a request for the method "itemService.find".
     *
     * This request holds the parameters needed by the the item server.  After setting any optional
     * parameters, call the {@link Find#execute()} method to invoke the remote operation.
     *
     * @param id
     * @return the request
     */
    public Find find(java.lang.Long id) throws java.io.IOException {
      Find result = new Find(id);
      initialize(result);
      return result;
    }

    public class Find extends ItemRequest<com.appspot.qr_search_api.item.model.Item> {

      private static final String REST_PATH = "find";

      /**
       * Create a request for the method "itemService.find".
       *
       * This request holds the parameters needed by the the item server.  After setting any optional
       * parameters, call the {@link Find#execute()} method to invoke the remote operation. <p> {@link
       * Find#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected Find(java.lang.Long id) {
        super(Item.this, "GET", REST_PATH, null, com.appspot.qr_search_api.item.model.Item.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Find setAlt(java.lang.String alt) {
        return (Find) super.setAlt(alt);
      }

      @Override
      public Find setFields(java.lang.String fields) {
        return (Find) super.setFields(fields);
      }

      @Override
      public Find setKey(java.lang.String key) {
        return (Find) super.setKey(key);
      }

      @Override
      public Find setOauthToken(java.lang.String oauthToken) {
        return (Find) super.setOauthToken(oauthToken);
      }

      @Override
      public Find setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Find) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Find setQuotaUser(java.lang.String quotaUser) {
        return (Find) super.setQuotaUser(quotaUser);
      }

      @Override
      public Find setUserIp(java.lang.String userIp) {
        return (Find) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public Find setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public Find set(String parameterName, Object value) {
        return (Find) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "itemService.findByCode".
     *
     * This request holds the parameters needed by the the item server.  After setting any optional
     * parameters, call the {@link FindByCode#execute()} method to invoke the remote operation.
     *
     * @param code
     * @return the request
     */
    public FindByCode findByCode(java.lang.String code) throws java.io.IOException {
      FindByCode result = new FindByCode(code);
      initialize(result);
      return result;
    }

    public class FindByCode extends ItemRequest<com.appspot.qr_search_api.item.model.Item> {

      private static final String REST_PATH = "findByCode";

      /**
       * Create a request for the method "itemService.findByCode".
       *
       * This request holds the parameters needed by the the item server.  After setting any optional
       * parameters, call the {@link FindByCode#execute()} method to invoke the remote operation. <p>
       * {@link
       * FindByCode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param code
       * @since 1.13
       */
      protected FindByCode(java.lang.String code) {
        super(Item.this, "GET", REST_PATH, null, com.appspot.qr_search_api.item.model.Item.class);
        this.code = com.google.api.client.util.Preconditions.checkNotNull(code, "Required parameter code must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public FindByCode setAlt(java.lang.String alt) {
        return (FindByCode) super.setAlt(alt);
      }

      @Override
      public FindByCode setFields(java.lang.String fields) {
        return (FindByCode) super.setFields(fields);
      }

      @Override
      public FindByCode setKey(java.lang.String key) {
        return (FindByCode) super.setKey(key);
      }

      @Override
      public FindByCode setOauthToken(java.lang.String oauthToken) {
        return (FindByCode) super.setOauthToken(oauthToken);
      }

      @Override
      public FindByCode setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (FindByCode) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public FindByCode setQuotaUser(java.lang.String quotaUser) {
        return (FindByCode) super.setQuotaUser(quotaUser);
      }

      @Override
      public FindByCode setUserIp(java.lang.String userIp) {
        return (FindByCode) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String code;

      /**

       */
      public java.lang.String getCode() {
        return code;
      }

      public FindByCode setCode(java.lang.String code) {
        this.code = code;
        return this;
      }

      @Override
      public FindByCode set(String parameterName, Object value) {
        return (FindByCode) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "itemService.save".
     *
     * This request holds the parameters needed by the the item server.  After setting any optional
     * parameters, call the {@link Save#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.qr_search_api.item.model.Item}
     * @return the request
     */
    public Save save(com.appspot.qr_search_api.item.model.Item content) throws java.io.IOException {
      Save result = new Save(content);
      initialize(result);
      return result;
    }

    public class Save extends ItemRequest<com.appspot.qr_search_api.item.model.Text> {

      private static final String REST_PATH = "save";

      /**
       * Create a request for the method "itemService.save".
       *
       * This request holds the parameters needed by the the item server.  After setting any optional
       * parameters, call the {@link Save#execute()} method to invoke the remote operation. <p> {@link
       * Save#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.qr_search_api.item.model.Item}
       * @since 1.13
       */
      protected Save(com.appspot.qr_search_api.item.model.Item content) {
        super(Item.this, "POST", REST_PATH, content, com.appspot.qr_search_api.item.model.Text.class);
      }

      @Override
      public Save setAlt(java.lang.String alt) {
        return (Save) super.setAlt(alt);
      }

      @Override
      public Save setFields(java.lang.String fields) {
        return (Save) super.setFields(fields);
      }

      @Override
      public Save setKey(java.lang.String key) {
        return (Save) super.setKey(key);
      }

      @Override
      public Save setOauthToken(java.lang.String oauthToken) {
        return (Save) super.setOauthToken(oauthToken);
      }

      @Override
      public Save setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Save) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Save setQuotaUser(java.lang.String quotaUser) {
        return (Save) super.setQuotaUser(quotaUser);
      }

      @Override
      public Save setUserIp(java.lang.String userIp) {
        return (Save) super.setUserIp(userIp);
      }

      @Override
      public Save set(String parameterName, Object value) {
        return (Save) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "itemService.update".
     *
     * This request holds the parameters needed by the the item server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.qr_search_api.item.model.Item}
     * @return the request
     */
    public Update update(com.appspot.qr_search_api.item.model.Item content) throws java.io.IOException {
      Update result = new Update(content);
      initialize(result);
      return result;
    }

    public class Update extends ItemRequest<Void> {

      private static final String REST_PATH = "update";

      /**
       * Create a request for the method "itemService.update".
       *
       * This request holds the parameters needed by the the item server.  After setting any optional
       * parameters, call the {@link Update#execute()} method to invoke the remote operation. <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.qr_search_api.item.model.Item}
       * @since 1.13
       */
      protected Update(com.appspot.qr_search_api.item.model.Item content) {
        super(Item.this, "PUT", REST_PATH, content, Void.class);
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Item}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Item}. */
    @Override
    public Item build() {
      return new Item(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ItemRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setItemRequestInitializer(
        ItemRequestInitializer itemRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(itemRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
